# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='value_list',
            new_name='value_set',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='product_list',
        ),
        migrations.AddField(
            model_name='product',
            name='tag_set',
            field=models.ManyToManyField(to='restshop.Tag'),
        ),
    ]
