# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0003_auto_20170827_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restshop.Product')),
            ],
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['product__title', 'sku']},
        ),
    ]
