# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0011_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['unit__product__title', '-is_main', 'image'],
            },
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='unit',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.AddField(
            model_name='unitimage',
            name='unit',
            field=models.ManyToManyField(to='restshop.Unit'),
        ),
    ]
