# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0012_auto_20170829_0950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='unitimage',
            options={'ordering': ['image']},
        ),
        migrations.RenameField(
            model_name='unitimage',
            old_name='unit',
            new_name='unit_set',
        ),
    ]
