# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0013_auto_20170829_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=31),
        ),
    ]
