# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0014_auto_20170829_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orderunit',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restshop.Order'),
        ),
        migrations.AddField(
            model_name='orderunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restshop.Unit'),
        ),
    ]
