# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0015_auto_20170830_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_set1',
            field=models.ManyToManyField(related_name='orders', through='restshop.OrderUnit', to='restshop.Unit'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_set',
            field=models.ManyToManyField(to='restshop.Unit'),
        ),
    ]
