# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0017_remove_order_unit_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='unit_set1',
        ),
        migrations.AddField(
            model_name='order',
            name='unit_set',
            field=models.ManyToManyField(through='restshop.OrderUnit', to='restshop.Unit'),
        ),
    ]
