# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0019_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='unit',
            name='num_in_stock',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
