# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0022_auto_20170905_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
