# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0023_auto_20170905_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitimage',
            name='unit_set',
            field=models.ManyToManyField(blank=True, to='restshop.Unit'),
        ),
    ]
