# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restshop', '0025_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restshop.Unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orderunit',
            name='unit_price',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
