# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restshop', '0027_auto_20171017_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='orderunit',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('RE', 'Rejected'), ('CO', 'Completed')], default='PE', max_length=2),
        ),
    ]
